(function () {
  'use strict';

  const assetBase = window.DRUZA_ASSET_BASE || '';
  const routeBase = window.DRUZA_ROUTE_BASE || '';
  const asset = (path) => (path ? assetBase + path : '');
  const route = (path) => routeBase + path;

  window.DRUZA_CATALOG = {
    products: [
      {
        id: 'anel-coracao-esmeralda',
        sku: 'EXEMPLO-ANEL-CORACAO-ESMERALDA',
        name: 'Anel Coração Esmeralda',
        category: 'aneis',
        categoryLabel: 'Anéis',
        stone: 'esmeralda',
        priceCents: 18900,
        installments: 'ou 6x de R$ 31,50 sem juros',
        image: asset('img/anel-coracao.jpg'),
        imageAlt: 'Anel de prata com pedra esmeralda em formato coração.',
        url: route('produtos/anel-coracao-esmeralda.html'),
        featured: true,
        related: false,
        realImage: true,
        description: 'Um coração de pedra verde sobre prata polida, pequeno no tamanho e marcante na presença.',
        detail: 'Produto de exemplo do protótipo: anel de prata 925 com pedra verde esmeralda em formato coração.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia verde esmeralda',
        finish: 'Ródio',
        measurements: 'Aro ajustável por tamanho selecionado',
        variationLabel: 'Tamanho do anel',
        sizes: ['14', '16', '18', '20'],
        gallery: [
          { image: asset('img/anel-coracao.jpg'), alt: 'Anel coração esmeralda, vista frontal.' },
          { image: asset('img/anel-paraiba.jpg'), alt: 'Anel com pedra Paraíba, referência de acabamento.' },
          { image: asset('img/pulseiras-riviera.jpg'), alt: 'Pulseiras riviera de prata, referência de brilho.' }
        ]
      },
      {
        id: 'pulseira-riviera-prata',
        sku: 'EXEMPLO-PULSEIRA-RIVIERA-PRATA',
        name: 'Pulseira Riviera Prata',
        category: 'pulseiras',
        categoryLabel: 'Pulseiras',
        stone: 'verde',
        priceCents: 15900,
        installments: 'ou 6x de R$ 26,50 sem juros',
        image: asset('img/pulseiras-riviera.jpg'),
        imageAlt: 'Pulseira riviera de prata com pedras verdes.',
        url: route('produtos/pulseira-riviera-prata.html'),
        featured: true,
        related: true,
        realImage: true,
        description: 'Uma pulseira de prata com brilho contínuo, pensada para acompanhar anéis e pontos de luz.',
        detail: 'Produto de exemplo do protótipo: pulseira riviera em prata com pedras verdes.',
        material: 'Prata 925',
        stoneLabel: 'Zircônias verdes',
        finish: 'Ródio',
        measurements: 'Comprimento de exemplo: 18 cm',
        variationLabel: 'Tamanho',
        sizes: ['Único'],
        gallery: [
          { image: asset('img/pulseiras-riviera.jpg'), alt: 'Pulseira riviera de prata com pedras verdes.' },
          { image: asset('img/anel-coracao.jpg'), alt: 'Anel coração usado como referência de combinação.' },
          { image: asset('img/anel-paraiba.jpg'), alt: 'Anel Paraíba usado como referência de combinação.' }
        ]
      },
      {
        id: 'anel-paraiba-quadrado',
        sku: 'EXEMPLO-ANEL-PARAIBA-QUADRADO',
        name: 'Anel Paraíba Quadrado',
        category: 'aneis',
        categoryLabel: 'Anéis',
        stone: 'paraiba',
        priceCents: 21900,
        installments: 'ou 6x de R$ 36,50 sem juros',
        image: asset('img/anel-paraiba.jpg'),
        imageAlt: 'Anel de prata com pedra Paraíba turquesa.',
        url: route('produtos/anel-paraiba-quadrado.html'),
        featured: true,
        related: true,
        realImage: true,
        description: 'A pedra Paraíba cria um ponto de cor luminoso sobre a prata, com presença limpa e elegante.',
        detail: 'Produto de exemplo do protótipo: anel quadrado em prata com pedra Paraíba turquesa.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia Paraíba',
        finish: 'Ródio',
        measurements: 'Aro ajustável por tamanho selecionado',
        variationLabel: 'Tamanho do anel',
        sizes: ['14', '16', '18', '20'],
        gallery: [
          { image: asset('img/anel-paraiba.jpg'), alt: 'Anel de prata com pedra Paraíba turquesa.' },
          { image: asset('img/anel-coracao.jpg'), alt: 'Anel coração como referência de acabamento.' },
          { image: asset('img/pulseiras-riviera.jpg'), alt: 'Pulseira riviera como referência de brilho.' }
        ]
      },
      {
        id: 'brinco-gota-esmeralda',
        sku: 'EXEMPLO-BRINCO-GOTA-ESMERALDA',
        name: 'Brinco Gota Esmeralda',
        category: 'brincos',
        categoryLabel: 'Brincos',
        stone: 'esmeralda',
        priceCents: 12900,
        installments: 'ou 6x de R$ 21,50 sem juros',
        image: '',
        imageAlt: 'Foto em breve do brinco gota esmeralda.',
        url: route('produtos/brinco-gota-esmeralda.html'),
        featured: false,
        related: true,
        realImage: false,
        placeholderDescription: 'Entrará uma imagem real do Brinco Gota Esmeralda em prata.',
        description: 'Uma gota verde delicada para iluminar o rosto com prata e brilho discreto.',
        detail: 'Produto de exemplo do protótipo: brinco gota em prata com pedra esmeralda.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia verde esmeralda',
        finish: 'Ródio',
        measurements: 'Medidas finais em breve',
        variationLabel: 'Tamanho',
        sizes: ['Único'],
        gallery: []
      },
      {
        id: 'argolinha-paraiba',
        sku: 'EXEMPLO-ARGOLINHA-PARAIBA',
        name: 'Argolinha Paraíba',
        category: 'brincos',
        categoryLabel: 'Brincos',
        stone: 'paraiba',
        priceCents: 14900,
        installments: 'ou 6x de R$ 24,83 sem juros',
        image: '',
        imageAlt: 'Foto em breve da argolinha Paraíba.',
        url: route('produtos/argolinha-paraiba.html'),
        featured: false,
        related: true,
        realImage: false,
        placeholderDescription: 'Entrará uma imagem real da Argolinha Paraíba com pedra verde.',
        description: 'Uma argolinha delicada com ponto verde Paraíba para uso diário.',
        detail: 'Produto de exemplo do protótipo: argolinha em prata com pedra Paraíba.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia Paraíba',
        finish: 'Ródio',
        measurements: 'Medidas finais em breve',
        variationLabel: 'Tamanho',
        sizes: ['Único'],
        gallery: []
      },
      {
        id: 'brinco-ponto-luz',
        sku: 'EXEMPLO-BRINCO-PONTO-LUZ',
        name: 'Brinco Ponto de Luz',
        category: 'brincos',
        categoryLabel: 'Brincos',
        stone: 'cristal',
        priceCents: 11900,
        installments: 'ou 6x de R$ 19,83 sem juros',
        image: '',
        imageAlt: 'Foto em breve do brinco ponto de luz.',
        url: route('produtos/brinco-ponto-luz.html'),
        featured: false,
        related: true,
        realImage: false,
        placeholderDescription: 'Entrará uma imagem real do Brinco Ponto de Luz em prata.',
        description: 'Um ponto de luz pequeno, limpo e fácil de combinar com outras peças.',
        detail: 'Produto de exemplo do protótipo: brinco ponto de luz em prata.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia cristal',
        finish: 'Ródio',
        measurements: 'Medidas finais em breve',
        variationLabel: 'Tamanho',
        sizes: ['Único'],
        gallery: []
      },
      {
        id: 'colar-ponto-luz-paraiba',
        sku: 'EXEMPLO-COLAR-PONTO-LUZ-PARAIBA',
        name: 'Colar Ponto de Luz Paraíba',
        category: 'colares',
        categoryLabel: 'Colares',
        stone: 'paraiba',
        priceCents: 17900,
        installments: 'ou 6x de R$ 29,83 sem juros',
        image: '',
        imageAlt: 'Foto em breve do colar ponto de luz Paraíba.',
        url: route('produtos/colar-ponto-luz-paraiba.html'),
        featured: false,
        related: false,
        realImage: false,
        placeholderDescription: 'Entrará uma imagem real do colar ponto de luz com pedra Paraíba.',
        description: 'Um ponto de luz Paraíba para usar sozinho ou em composição com anéis e pulseiras.',
        detail: 'Produto de exemplo do protótipo: colar ponto de luz em prata com pedra Paraíba.',
        material: 'Prata 925',
        stoneLabel: 'Zircônia Paraíba',
        finish: 'Ródio',
        measurements: 'Corrente de exemplo: 45 cm',
        variationLabel: 'Tamanho',
        sizes: ['Único'],
        gallery: []
      }
    ]
  };
})();
