-- Executar depois de db/security-p0-acl-lockdown.sql.
--
-- Teste exclusivo de metadados. Nao consulta tabelas de negocio, nao chama
-- RPCs e termina em ROLLBACK para remover os objetos de prova.

begin;

create function public.__druza_p0_function_probe()
returns integer
language sql
as 'select 1';

create table public.__druza_p0_table_probe (
  id bigint generated by default as identity primary key
);

create sequence public.__druza_p0_sequence_probe;

do $p0_smoke$
declare
  v_signature text;
begin
  if exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prosecdef
      and (
        has_function_privilege('anon', p.oid, 'EXECUTE')
        or has_function_privilege('authenticated', p.oid, 'EXECUTE')
      )
  ) then
    raise exception 'p0_smoke_security_definer_exposed';
  end if;

  if exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'private'
      and (
        has_function_privilege('anon', p.oid, 'EXECUTE')
        or has_function_privilege('authenticated', p.oid, 'EXECUTE')
      )
  ) then
    raise exception 'p0_smoke_private_function_exposed';
  end if;

  for v_signature in
    select unnest(array[
      'public.consume_rate_limit(text,text,integer,integer)',
      'public.create_reserved_order(uuid,uuid,jsonb,text)',
      'public.claim_payment_attempt(uuid,uuid,text)',
      'public.cancel_payment_attempt(uuid,uuid,text)',
      'public.apply_payment_event(text,text,uuid,text,text,integer,text,timestamptz,timestamptz)',
      'public.list_payment_reconciliation_candidates(integer)',
      'public.reconcile_payment_not_found(uuid,uuid)',
      'public.release_expired_pending_reservations(integer)',
      'public.admin_move_inventory(uuid,uuid,text,integer,text,text,integer,text,text)',
      'public.admin_save_product(uuid,uuid,jsonb,jsonb,integer)',
      'public.product_stock_snapshot()',
      'public.admin_dashboard_metrics()',
      'public.admin_customer_summary(integer,integer)',
      'public.admin_find_user_ids(text)',
      'public.admin_find_order_ids(text)'
    ])
  loop
    if to_regprocedure(v_signature) is null then
      raise exception 'p0_smoke_missing_function:%', v_signature;
    end if;
    if not has_function_privilege(
      'service_role', to_regprocedure(v_signature), 'EXECUTE'
    ) then
      raise exception 'p0_smoke_service_role_missing:%', v_signature;
    end if;
    if has_function_privilege('anon', to_regprocedure(v_signature), 'EXECUTE')
       or has_function_privilege(
         'authenticated', to_regprocedure(v_signature), 'EXECUTE'
       ) then
      raise exception 'p0_smoke_client_can_execute:%', v_signature;
    end if;
  end loop;

  if not has_function_privilege(
    'anon',
    'public.effective_price_cents(integer,integer,timestamptz,timestamptz)',
    'EXECUTE'
  ) or not has_function_privilege(
    'authenticated',
    'public.effective_price_cents(integer,integer,timestamptz,timestamptz)',
    'EXECUTE'
  ) or not has_function_privilege(
    'service_role',
    'public.effective_price_cents(integer,integer,timestamptz,timestamptz)',
    'EXECUTE'
  ) then
    raise exception 'p0_smoke_price_function_grant_missing';
  end if;

  if has_function_privilege(
    'anon', 'public.__druza_p0_function_probe()', 'EXECUTE'
  ) or has_function_privilege(
    'authenticated', 'public.__druza_p0_function_probe()', 'EXECUTE'
  ) or has_function_privilege(
    'service_role', 'public.__druza_p0_function_probe()', 'EXECUTE'
  ) then
    raise exception 'p0_smoke_future_function_default_open';
  end if;

  if has_table_privilege('anon', 'public.__druza_p0_table_probe', 'SELECT')
     or has_table_privilege(
       'authenticated', 'public.__druza_p0_table_probe', 'SELECT'
     ) or has_table_privilege(
       'service_role', 'public.__druza_p0_table_probe', 'SELECT'
     ) then
    raise exception 'p0_smoke_future_table_default_open';
  end if;

  if has_sequence_privilege(
    'anon', 'public.__druza_p0_sequence_probe', 'USAGE'
  ) or has_sequence_privilege(
    'authenticated', 'public.__druza_p0_sequence_probe', 'USAGE'
  ) or has_sequence_privilege(
    'service_role', 'public.__druza_p0_sequence_probe', 'USAGE'
  ) then
    raise exception 'p0_smoke_future_sequence_default_open';
  end if;

  raise notice 'P0 ACL smoke test: OK';
end
$p0_smoke$;

rollback;
